# Generated by Django 5.2.7 on 2025-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок публикации", max_length=100, verbose_name="Заголовок"
                    ),
                ),
                ("content", models.TextField(help_text="Введите описание продукта", verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото продукта",
                        null=True,
                        upload_to="blog/image",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Отметьте для публикации", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Количество просмотров статьи", verbose_name="Количество просмотров"
                    ),
                ),
            ],
        ),
    ]
