# Generated by Django 4.2.2 on 2026-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish_product",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Значение публикации"),
        ),
    ]
